title: Who is AppleTechPro?
author: iamjavlon
email: javlon20048@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Let's find out who really AppleTechPro is. What does he do and what's the purpose of his channel.

# social links
twitter_username: JavlonAbdumuta1 # DO NOT include the @ character, or else the build will fail!
github_username:  iamjavlon # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
